### PR TITLE
Dependency injection/services

### PR DESCRIPTION
**Pull request by UPovilas**
Dependency injection added where possible, changes to make the project follow the Single Responsibility principle.

### CODE REVIEW

**Comment by UPovilas** [comment]
Do not approve this yet, solving conflicts

**Comment by UPovilas** [comment]
Now it should work

**Comment by UPovilas** [comment]
Ignore the typo of the folder "Services", will be fixed in next pull request 😃

**Review by elvinukas — APPROVED** [review]
Good job!

**Review by RytasV — APPROVED** [review]
Nice

**Pull request merged**
