### PR TITLE
Cosmetic changes

### PR DESCRIPTION
**Pull request by elvinukas**
+ Database table Statistics now supports storing Gamemode field
+ Fixed a bug where Game would not store Gamemode
+ Removed "Išsaugoti statistiką" button. All player attempts are now registered automatically.
+ Added gamemode selection property.
+ Implemented hardcore gamemode, where the user cannot input any mistakes.
+ many other small little fixes

### CODE REVIEW

**Comment by elvinukas** [comment]
bandžiau taisyt merge confliktą, dar kažkokie errorai nematyti atsirado :) taisau...

**Comment by elvinukas** [comment]
Viskas gerai! Pasirodo tiesiog turėjau vėl susisettupinti appsettings.json, nes connection stringo nėra githube :)

**Review by UPovilas — APPROVED** [review]
Works as intended. Great job!

**Review by RytasV — APPROVED** [review]
Great job!

**Pull request merged**
